version: '{branch}-{build}'
environment:
  CLIENT_SECRET:
    secure: gMz4Rk7Fiu9R18B9eAG0LPQdm6KE2pINcGLKxAH2i5BIozDO6EqiqfmquC/FWB1p7gKhdpqwESXUqpRcVL9g5sZZBajZWpr2vY2MRLBlmW1Hrsi59jHTFs7qfrqtBgOcmHwk6rhukC//41z53mcIQ4vM+HD6glCaB4+CsnXoWzMJJ9aif2MRE3MFdVO9kSVmVs0EcEJBFU9VebtS7XHGuy+U3e6L6YJpvOcf5PmK18jIAkZUfac+1eWgN0s/ylkmCIDSHMfiMu+jy2PN0vLTC4NPSr4OMrgrirHB4ROVMkSDExZgyrHsw6Xarr/teZeJeFFRlatIG+rcfDijzN66rp/hQ/DJaiGNDqwx+sws4fqkS9dPcTuaT8Ui+elAa7099jVf6qaDJsCi7hjp+BfiC0PR7x+6bo6S+d+BM8HrIEEEwoq+HRSbV+4D82Xgbu2nQPudEpbtKMtZY25XMebT6rZcr3VhrnAfCl32uHdMC8ODFCOTnrQ0cvaNkQfCN/5q807QOG901Rpkd2EEv6eSLyYqqH+kKgobhQ/3NGxOgOSXcGXrlC67v3X96eseSM4vnTUe9vMV2fsq9SQ8Q0fevFV4q/2mj9jT971/ZRdV/zBUDsqK4VlaC4qEp0uDsSletZplUOasVKvaSpfnD7OqpEu1m7gcByzpkkZmoelZxOP+W7fvmJJKDxVpoeIyTo1k0aQLUgyOiDICIXGO1ZsCQbY/hoFzdX0xAViDJW+UB33WzsXhYVdm5j+GHFMKFgF4/vxAhDdiMRnFGFZFT39YxxexRKe1/WBtJhb/bHEaoFXBW6Qbvm8yzOO+JlqVaU0HpQYh34cL4uxHki2yhq5/TmWr6ZxxpXUqu7alPSXnfPmT+7LA9/csRoZOGh46McDjVZjfqH1Rboz8YkSNgWTad7P9BLHmkmuBNv8GT399TIKOi9E6FJHU30BtHSCf0riQV6hhdhh+1tMsZtNYOOpYPl3D/0jUuborhp5Sbx0f9EXsm4UBUoBm2VBnqUuEO5nL1PINYS4RfqlDFkWYyMZRKotaKj3laZwKpxYuTJN3FwlNFx82zvHXYjhEv+i7W0F/2Zns/G3ndYtBeMScn/bE71VAJitn5U9SoAgfzu2VmK+VJu0G1UVUXn13RFPOsOV/doD9sGjNkbbBeKKcMswmv/u3VzsXyynbORLzW4iaUQBo+XcwIusF6CoZ9mqo0fClHhc3rnwCNFl5R0+KU4s0JoeHAbqFndKiR0lNapoqFCLae4x4QZkU1z3JtFplOvJAaRYjadZMfd729eKAEiNXu01nHrALU9W0wEZ6XtMTJiKMDg186MadFiRLGAVI9kP/5PkEYkYGUqAQBKvHgrQoYxMVIIW4K3b15tUqAdzx9eN1+MoOiMkESB3Wo3W6yCUwrIcWr4wFwgg/5WxqNEA4H2kzfpLHsU0bAPLa/GkAU223M4YQCFF5gtoVodh6wNNrYn4Me3OzMFbGC7w15zIKQuk08nNJ8pmkJMkw925JW9jSgslDFhz0T4ElQgIy8XiAt8++8EKqqPZPMNAHKHzwbgAgN+Ze7AAo1V1UjeWtbVng3FtIe6Ujrpbn+LtNrSwPYssZKmW1Y4nWY2zA+Luq0z0EW8KSMQCMlh7jTJzgnd/SQcYpyY9KKWjv8yO71wCYguNqRitqoV3UdHEh8VbNJDEC8zNFoThH0gkK+IBvbNAW/bPohO0LDT2wxc7l7rTmm0kQSHgIeNvUO97n1ApsMHO6Sf7zzclTKlwq/41bRbS+R1uauXFIGoI1LZpb/J4nE5OQPJwlNOE3MaWQQkcBNUVfkUjHXvv3kS+foiIGFDqA3JRATGb+dsrprzGUa1n9Ghm4LxE4QC4nbabVRjCGkTLlHwtfsPcBI+vtUj4bq+l8PKMBfpFX6OeyRjQrPUs9BIk5HH4wFNL14glqMVcNu+Qu7PjbfUE5gPqdrQDYMVSIRLfQSM1hwmgYif1wzb+WPxWCV/il9k7M+gJ3QL0vRuhXVOi4VBdYsEd8yGye22qr4r821TaqLT3V2exl2Z5iqU+Hv6xn2XYTgCV550IYow==
  MOCHA_SECRET:
    secure: sheXTHMSO48OPMaUWP7W7pBTGpn9b8cl7KLObXjX7mgtXXPlUJmXiKTruhK5cDHJhhdyavJIF/HvG3tjppk0CFFB88aZ37SbIUKsuw6hLX0NPOKwuWvx8Ene1MJ7WPojEnFtO4SE0hWJyGwH4OYFymYJ9xD46SlHusm7/jLCTeY05e1llD6UbrRDD3bI7vmaPJaLXm8HdLyAuU5g3D/N4YXxvbWZzDwcynMDa87IKOLyBvSZlbmUjhVqAwxMsiJsPVY142DO1TtMBLiCOHaFQMenRZ+QlFLoXLcNQkYIhWjDmsHHpB4lh8kT5ucfwV1skyp5G0QH2ZCpl/60TmuX/Cd35GDq2ipGjIB7B6DUnIZXBYQDGDWVA5nEuMz9DZesWzVxNqX4nCM90s482gY4D5KKtcDx189e/qM1cDRrmDwnr4xPUnZLHx1omGYs7As8+oM8AOaLRByFe507o/cMFENIe5k6giSsg6M9UOXXIceKKtPah/iTNI48JZBLtdbrWW1iV2U3CuPEjTWL/XczZoOwEWzJ9Jc1DKJ4HQsm9sqga2ax8txh31A2H1aRamIANRiSLvb3EXrfhN5qdqLQKVODX2KUTAAreSNENCd8ZVOLl3MjCn/Yt5oq8XLOZyyKpo2g/MpWrtpiqXjz/mYn0Wzr4MnoInWE94l0IQmUZ/R2rqVDpPu7TCMt8m7b02Kt9E4PFA9K8HppRC2ZHjkS+VFe15Ps5BCp1s04936gBbM/5sroH9c2VP8I62aMBHe74oudBqGA5bgBeAB/P8NUOgLXr3AsIxzgdr9LzNtlBX049IiDR4Bq11qnniMwaCVLST8lwC3iWtYLNNvsKY04PsTmHsZThmM4agkgW7HqMy4JGuYs7sHbuuV2kdzoUe5MHZhkfg8Znxzgj3INA8S0FPNwTfcLwDuCOjPaP5K4rVWFziFcxBHRoUVFpyYO6ueUwrfljQTk1efeRNAL8CGNUxWZcbHrzWzR0m1iGdMuaM6b03Mqol2TIAY0N2CmSIveHzTcoUuQL4yO7wBeqweS9tcNoMb08oB7mumaHkz2zI3wogGSmYuxEVcnVTMqXN4zEG/VJKXnNAxjyWrJCvJvJIcH2cE9oVyD1Cb1kQB0jaTkjlWjw4jUnG933Kdt8/RZ3kn0B7EPjvzMoKqykeCJIbmFPNz2WWVkoA7T8RFUT3v+imUflMeLQnTxGO+mc7bZsrfn1A48t+x2Ap9Cf1w2dFM9PH02Sv17OLYbAedxXSeMfFrdSJOID+U7x3H+IQfVlPvCcmeVK0bmARpubMIcTLtGxVehRb6YqCc3ql5gZIFB1jbY1lKblW4Kl7BUlwvkJxiJdN28F1VygRoiFBWi/QA6RE+3rVNjJRJROOrI8MQADoZeDAQjYr5rsdCgeZtulJPEtqn7GfiOAxTct8TaCXAOYdp6XcRiEBq+GiC6y2VBILiY+CnAHt6uyUDRdISo/iCbJcRHv3XqXvx3fKfOo3dC7n2IwoOjBVEzdKNrL66GHl1ISxK149YPAtKoHlSXg9jWU7zRSvYYhLjwuQl+jdVbxmOZtlXTeTc4vng0Vpm7S+SOoACbzVeV0AS0rGITEasg19UY9gsgFWx3bXMdMzFP+s8pSnJBnq9A2Fs5bptqqtDVe2G3v90yKW2g3VRrmhMjYO3SMeyqW42DReEFeD57Vh0BkoSBQvmGJsTLRV5QelL3wqdXIu0O9RX7M3A587ugIn79wS/lvg8sdfkdlTiByJK50g7Skg3ECH4HMCKPzMUm+EJM4+YafhYvtC2CUEPRpipeg53Ux6sJ54lv/ZvW6V7kByVgPl3IeZYVc34vQC/k23B5ErU5e5vgFXhUPUVH1r1SP/jYoOv0sCJbGRxJHmeZqqRfE5/Firtahw40aeSJqyiZkLhOWqCIvz+UWDSBUWcvCIRhmYABfwzNyo2N8+Ecj/4zHRqZI4qyy8s=
  matrix:
    - nodejs_version: "10.8.0"
  # Prepare Nodegit 
  npm_config_target: 3.1.9
  npm_config_arch: ia32
  npm_config_target_arch: ia32
  npm_config_disturl: https://atom.io/download/electron
  npm_config_runtime: electron
  npm_config_build_from_source: true

platform:
  - x86

cache:
  - node_modules

skip_branch_with_pr: true
skip_tags: true
matrix:
  fast_finish: true

install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: $env:package_name = (Get-Content -Raw -Path package.json | ConvertFrom-Json).name
  - ps: Update-AppveyorBuild -Version "$env:package_version"
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - ps: echo "version $env:package_version {version}"
  - node --version
  - git reset --hard HEAD

  # Update NPM
  - npm install -g npm
  - npm --version

  # Update node-gyp
  - npm install -g node-gyp

  # Install electron first
  #- npm install --only=dev
  - npm install
  - npm list --depth 0 

  # Install build tools
  - npm install -g bower
  - bower --version

  # Install bower packages
  - bower install

  # Create client.js
  - ps: node build/appveyor.js "$env:CLIENT_SECRET" "$env:MOCHA_SECRET"

build_script:
  - node --version
  - npm --version
  - npm run build:win

artifacts:
  - path: build\dist\squirrel-windows-ia32\*.exe
  - path: build\dist\squirrel-windows-ia32\*.nupkg

deploy:
- provider: GitHub
  appveyor_repo_tag: true
  release: $(appveyor_build_version)
  auth_token:
    secure: LKXeApGg9OVrhdUpPe0SawGyBdD7Mjb3sl1NSnDOFslNlIrTZC8fEO/IfFq7x85y
  repository: xgeek-net/pipeline
  prerelease: true
  force_update: true
  on:
    branch: master

branches:
  only:
  - master
